# Site settings
title: Lucas Barbosa
email: lucas.barbosa.work@hotmail.com
url: https://lucasbarbosagit.github.io
description: "Portfolio de Lucas Barbosa, contendo projetos envolvendo as áreas de Desenvolvimento Web e Design"
skills: "Desenvolvedor Web e Designer"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Lucas Barbosa
  location: Localização
  social: Redes Sociais
  credits: Créditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
    #url: http://twitter.com/
  - title: behance
    url: https://www.behance.net/Lucas-Barbosa 
  - title: instagram
    url: https://www.instagram.com/walking_on_the_sunn/
  #- title: stack-overflow
   # url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/lucasbarbosagit

# Postal address (add as many lines as necessary)
address:
  - line: Piracicaba - SP
  - line: Brasil

# Credits content
credits: 'Site criado com Jekyll, usando o tema Freelancer por: <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
